services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - db
    env_file:
      - .env.test

  db:
    image: mysql:8.4.4
    container_name: db
    restart: always
    # ports:
    #   - 3306:3306
    env_file:
      - .env.test
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 20s

volumes:
  db:
